### PR TITLE
Pull plugin and themes to latest tag, if no tags are present, pull master/main branch

### PR DESCRIPTION
**Pull request by cschindlbeck**
I like the idea of this plugin, but currently it crashes if plugins/themes are checked out to a specific version (detached HEAD) instead of master/main branch

I have the following suggestions and this update takes care of the following:

- Fixes bug if plugins/themes are on a detached HEAD, a pull wrt master/main is still possible if it exists
- Checks out plugins/themes to latest tag instead of master/main 
- Checks out plugins/themes to master/main if no tags are present
- More verbose output to which tag plugins/themes are updated, if they are skipped, or pulled to latest master/main

full_autoupdate

Would be great if this could be reviewed carefully, i have tested it against a couple of scenarios and it works for me

### CODE REVIEW

**Comment by Pilaton** [comment]
Thank you! I will definitely check it out

**Comment by cschindlbeck** [comment]
What's the reason this was closed?

**Comment by Pilaton** [comment]
There are many problems with editing. 
For example, using `cd` in scripts is very bad practice. 
I will release my solution.

**Comment by cschindlbeck** [comment]
Can you comment on why cd is "very bad practice"? It could be changed back to git -C

**Comment by Pilaton** [comment]
You can improve your edit and I will definitely accept it! 🙏

**Pull request closed without merging**
